### ISSUE TITLE
bin edges in s2_response_er.csv 

### ISSUE THREAD

**Issue by paoloagnes** [XENON1T/s2only_data_release#1]
Hi there, 
I just found that the bin edges in s2_response_er.csv are the same of the s2_response_nr.csv and they don't match the bin centers 

e.g. the first line: 
energy_kev,energy_bin_start_kev,energy_bin_end_kev...
0.05,0.37434095493010494,0.42488496802771936...

**Comment by JelleAalbers** [comment]
Thanks for reporting Paolo! We'll update the file soon; in the meantime, you can add/subtract half the difference between the bin centers to find the right/left bin edges approximately.

**Comment by JelleAalbers** [comment]
The corrected file has been merged; just let us know if you find any other issues.
